-- MySQL Script generated by MySQL Workbench
-- 10/08/15 19:28:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BurritoBar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BurritoBar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BurritoBar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BurritoBar` ;

-- -----------------------------------------------------
-- Table `BurritoBar`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`User` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(16) NOT NULL COMMENT '',
  `guest` TINYINT(1) NULL COMMENT '',
  `creditProvider` VARCHAR(20) NOT NULL COMMENT '',
  `ccNum` INT NOT NULL COMMENT '',
  `firstName` VARCHAR(20) NOT NULL COMMENT '',
  `lastName` VARCHAR(20) NOT NULL COMMENT '',
  `loggedIn` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `ccNum_UNIQUE` (`ccNum` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Orders` (
  `orderID` INT UNSIGNED NOT NULL COMMENT '',
  `customerID` INT UNSIGNED NOT NULL COMMENT '',
  `timeOrdered` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`orderID`)  COMMENT '',
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC)  COMMENT '',
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC)  COMMENT '',
  CONSTRAINT `fk_Orders_User`
    FOREIGN KEY (`customerID`)
    REFERENCES `BurritoBar`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Items` (
  `itemName` VARCHAR(20) NOT NULL COMMENT '',
  `itemType` VARCHAR(20) NOT NULL COMMENT '',
  `itemPrice` INT UNSIGNED NOT NULL COMMENT '',
  `itemID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`itemID`)  COMMENT '',
  UNIQUE INDEX `itemID_UNIQUE` (`itemID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Burrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Burrito` (
  `burittoID` INT UNSIGNED NOT NULL COMMENT '',
  `orderID` INT UNSIGNED NOT NULL COMMENT '',
  `toppings` INT NULL COMMENT '',
  `sauces` INT NULL COMMENT '',
  `quantity` INT UNSIGNED NULL COMMENT '',
  `meatID` INT UNSIGNED NOT NULL COMMENT '',
  `drinkID` INT UNSIGNED NOT NULL COMMENT '',
  `tortillaID` INT UNSIGNED NOT NULL COMMENT '',
  `sideID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`burittoID`)  COMMENT '',
  UNIQUE INDEX `burittoID_UNIQUE` (`burittoID` ASC)  COMMENT '',
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC)  COMMENT '',
  UNIQUE INDEX `meatID_UNIQUE` (`meatID` ASC)  COMMENT '',
  UNIQUE INDEX `drinkID_UNIQUE` (`drinkID` ASC)  COMMENT '',
  UNIQUE INDEX `tortillaID_UNIQUE` (`tortillaID` ASC)  COMMENT '',
  UNIQUE INDEX `sideID_UNIQUE` (`sideID` ASC)  COMMENT '',
  CONSTRAINT `fk_Burrito_Orders1`
    FOREIGN KEY (`orderID`)
    REFERENCES `BurritoBar`.`Orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burrito_Items1`
    FOREIGN KEY (`meatID`)
    REFERENCES `BurritoBar`.`Items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burrito_Items2`
    FOREIGN KEY (`drinkID`)
    REFERENCES `BurritoBar`.`Items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burrito_Items3`
    FOREIGN KEY (`tortillaID`)
    REFERENCES `BurritoBar`.`Items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burrito_Items4`
    FOREIGN KEY (`sideID`)
    REFERENCES `BurritoBar`.`Items` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Toppings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Toppings` (
  `toppingID` INT UNSIGNED NOT NULL COMMENT '',
  `toppingName` VARCHAR(20) NOT NULL COMMENT '',
  `toppingPrice` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`toppingID`)  COMMENT '',
  UNIQUE INDEX `toppingID_UNIQUE` (`toppingID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Sauces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Sauces` (
  `sauceID` INT UNSIGNED NOT NULL COMMENT '',
  `sauceName` VARCHAR(20) NOT NULL COMMENT '',
  `saucePrice` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`sauceID`)  COMMENT '',
  UNIQUE INDEX `sauceID_UNIQUE` (`sauceID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BurritoBar`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BurritoBar`.`Session` (
  `sessionID` VARCHAR(256) NOT NULL COMMENT '',
  `sessionStart` DATETIME NOT NULL COMMENT '',
  `lastUse` DATETIME NOT NULL COMMENT '',
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`sessionID`)  COMMENT '',
  UNIQUE INDEX `sessionID_UNIQUE` (`sessionID` ASC)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '',
  CONSTRAINT `fk_Session_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `BurritoBar`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
